[package]
name = "libblkid-rs-sys"
version = "0.1.0"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2018"
description = "Low level bindings for libblkid"
license = "MPL-2.0"
documentation = "https://docs.rs/libblkid-rs-sys"
homepage = "https://stratis-storage.github.io"
repository = "https://github.com/stratis-storage/libblkid-rs"

[build-dependencies]
bindgen = "0.57.0"
cc = "1.0.45"
