---
name: libblkid cargo CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
    paths:
      - '**/Cargo.toml'
  pull_request:
    branches: [master]
    paths:
      - '**/Cargo.toml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks-with-ci-repo:
    strategy:
      matrix:
        include:
          # yamllint disable rule:line-length
          - task: |
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f36 IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=f36 IGNORE_ARGS="--ignore-category low" make -f ../../Makefile check-fedora-versions
    runs-on: ubuntu-20.04
    container:
      image: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          libblkid-devel
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: 1.64.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
          override: true
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}
        working-directory: ./ci/dependency_management
